apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.sbt.tunnel'
    compileSdk 34

    defaultConfig {
        applicationId "com.sbt.tunnel"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.11.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    constraints {
        implementation('org.jetbrains.kotlin:kotlin-stdlib') {
            version { strictly '1.9.24' }
        }
    }
}
